// One-shot: pull the Latin subsets of the two chosen faces from Google Fonts
// and write a local @font-face sheet. Re-run only when a face or weight changes.
import fs from 'node:fs/promises'
import path from 'node:path'

const OUT_FONT = new URL('../assets/fonts/', import.meta.url)
const OUT_CSS = new URL('../assets/css/fonts.css', import.meta.url)

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36'

const FAMILIES = [
  { spec: 'Barlow:wght@400;500;600;700', slug: 'barlow', keep: ['latin', 'latin-ext'] },
  { spec: 'Azeret+Mono:wght@400;500;600', slug: 'azeret-mono', keep: ['latin', 'latin-ext'] },
]

// 'Azeret+Mono' in the query string arrives as font-family: 'Azeret Mono'.
const familyKey = (spec) => spec.split(':')[0].replace(/\+/g, ' ')

const cssUrl = `https://fonts.googleapis.com/css2?${FAMILIES.map(
  (f) => `family=${f.spec}`,
).join('&')}&display=swap`

const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } })
if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`)
const css = await res.text()

// Google emits "/* subset */\n@font-face { ... }" blocks. Keep the ones we want.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)]

await fs.mkdir(OUT_FONT, { recursive: true })
await fs.mkdir(new URL('../assets/css/', import.meta.url), { recursive: true })

const out = [
  '/* Self-hosted subsets. Generated by tools/fetch-fonts.mjs - do not hand-edit. */',
  '',
]
let downloaded = 0

for (const [, subset, block] of blocks) {
  const family = /font-family:\s*'([^']+)'/.exec(block)?.[1]
  const weight = /font-weight:\s*(\d+)/.exec(block)?.[1]
  const url = /url\((https:\/\/[^)]+\.woff2)\)/.exec(block)?.[1]
  const range = /unicode-range:\s*([^;]+);/.exec(block)?.[1]
  if (!family || !weight || !url || !range) continue

  const slug = FAMILIES.find((f) => family === familyKey(f.spec))?.slug
  if (!slug) continue
  if (!FAMILIES.find((f) => f.slug === slug).keep.includes(subset)) continue

  const file = `${slug}-${weight}-${subset}.woff2`
  const bin = await fetch(url, { headers: { 'User-Agent': UA } })
  if (!bin.ok) throw new Error(`${url} responded ${bin.status}`)
  await fs.writeFile(new URL(file, OUT_FONT), Buffer.from(await bin.arrayBuffer()))
  downloaded += 1

  out.push(
    '@font-face {',
    `  font-family: '${family}';`,
    '  font-style: normal;',
    `  font-weight: ${weight};`,
    '  font-display: swap;',
    `  src: url('../fonts/${file}') format('woff2');`,
    `  unicode-range: ${range.trim()};`,
    '}',
    '',
  )
}

await fs.writeFile(OUT_CSS, out.join('\n'))
console.log(`wrote ${downloaded} woff2 files + ${path.basename(OUT_CSS.pathname)}`)
